// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: redUpgrade.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const redUpgrade = `-- name: RedUpgrade :exec
UPDATE users
SET is_chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) RedUpgrade(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, redUpgrade, id)
	return err
}
